logo: Metzmacher<span>.me</span>
title: Metzmacher.me
description: Persönliche Webseite von Kathrin & Thomas Metzmacher
permalink: ':title/'
baseurl: ""
url: "http://localhost:3000"

# Banner settings
video: mountains.mp4
banner-title: Metzmacher.me
banner-desc: Persönliche Webseite von Kathrin & Thomas Metzmacher

# Author settings
author-pic: face.jpg
author-name: Kathrin & Thomas Metzmacher
about-author: Germany, Taucha bei Leipzig
about-author-description: ...
email: kontakt@metzmacher.me
website: http://www.metzmacher.me/

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
